export const historyDoc = {
  id: 'history', title: 'Verify historical behavior',
  description: 'Inspect past sessions and recordings through o11 without a separate provider connection.',
  markdown: `# Verify historical behavior

Use only the connected o11 MCP endpoint or CLI. o11 reads its configured sources on the server. A coding agent does not need a separate PostHog connection, provider login or analytics credential. Inspect each tool's current schema with o11 tools describe before calling it. If a required tool is unavailable, report the missing o11 capability or permission; do not switch to a provider connector.

For new setup, investigate native o11 event receipts, coverage and recordings. PostHog import controls below apply only to existing PostHog routines and historical investigations; they are not prerequisites for new o11 capture. Missing historical o11 coverage cannot be reconstructed by installing tracking today.

Start with o11_setup, organization_current, engagement_capabilities, signals_sources and analytics_status. Verify the workspace, source ID, environment, granted scopes and import progress. Reuse returned IDs. Query independent discovery calls together and retain their results for this investigation. Recheck state after configuration changes.

For counts, order and first-session rules, start with recorded events. Discover the action and session fields with signals_resources and signals_sample. Build the exact structured definition, call signals_check, then signals_previewEvents. A preview can run without saving or activating a routine. Set imported only when inspecting the imported corpus; a source preview and an imported preview can have different coverage. Inspect findingPage and pendingPage for total, returned and nextOffset. Page findings with findingOffset and findingLimit; page pending absence checks independently with pendingOffset and pendingLimit. Retain the returned previewAsOf and previewFingerprint for either cursor, and use a new mutation operation ID for each distinct page input. Follow both cursors when the investigation needs all findings and pending checks. An oversized evidence record or coverage summary produces an explicit refusal; narrow the preview window or source scope before a new preview, and keep that investigation unverified until evidence is available. o11 rejects paging when late data changes the evidence. Display pagination preserves the full scan complete/coverage result. Follow returned pagination and inspect complete, reason and coverage fields. An empty or truncated preview cannot establish absence. The preview window selects candidates; it must not define the start of a customer's history.

When a history check blocks setup, inspect analytics_status and firstSessionHistory.coverageComplete, complete and unconfirmedCustomerCount. Inspect scheduled/manual import availability, job progress and errors. Distinguish an import that is running, paused, unavailable or finished from a partial source query and missing or tied session identities. Say earlier sessions are loading only when the source reports an active import; for a paused or unavailable importer, name the required control or server change and its owner. Do not ask the user to “confirm complete history.” If an import is running, explain that earlier sessions are still loading and why they are needed, report available progress, and link to Integrations to check source status. If the import has finished, identify the failed query or identity check and who can repair it; say which check remains unknown when the tools do not expose the cause. Give a cause-specific next action and rerun validation after the change. Use a label such as “Load earlier Excel sessions” only when its action can start that import; otherwise name the operator action. Loading history does not require the user to run recurring sync commands. If signals_check reports that first-session monitoring needs hourly imports, direct the source owner to set the sync interval to 1 hour in Integrations, then recheck the rule.

If analytics_status reports scheduled:false and manual:true, an authorized analytics_control call with action:sync starts manual imports. Follow more:true with analytics_continueImport using the same organization, environment and connector ID. These controls require o11:send because imported activity may wake outreach; request that scope through explicit OAuth consent when the grant lacks it. Keep the automatic-import pause in place. Recheck analytics_status after each page or error; more:false can also mean a lease, due-time or provider error, so it does not establish that history is complete. In the UI, loading continues while the Integrations page stays open and can be continued there later.

An event preview is observational and does not enroll customers or send messages. After a timeout, inspect o11_operation_status; when its recovery permits a fresh signals.previewEvents call, use a new operation ID and restart from the first page. A running or uncertain preview receipt is not evidence of no matches. This recovery applies only to the named preview; retain the existing receipt and reconciliation protections for publication, activation and delivery.

For “five messages in the first Excel session,” count unique message events in one session. Determine the earliest Excel session from all recorded Excel activity, including sessions with zero messages, then check its message count. A first web session does not establish the first Excel session. Keep source identity, verified customer identity links and session IDs distinct. Exclude later sessions, counts spread across sessions, missing identities, ambiguous ordering and incomplete imports. Source history proves only retained recorded activity; it cannot recover erased recordings or activity that was never captured. Verify the deployed schema supports the first-session condition; a history query used during setup is not a live monitoring rule.

Use research_sessions to inspect recording metadata and research_customer to follow the customer's earlier sessions. Use research_recordingDetail, research_recordingActivity, research_history and research_report for saved evidence and prior analysis. Follow their cursors and report pages when the claim requires them. A recording list does not count messages or prove complete event history. Use recording evidence when the behavior cannot be established from events, or to inspect a discrepancy. Existing archived evidence can be read through o11_read_artifact; respect its size limit and use paginated reports for larger artifacts. Do not download recordings or run a model over every recording to count structured events. Archive preparation is a separate mutation; request it only when needed and authorized. Historical analysis tools that can send owner previews or execute contact actions require separate authorization. Reading existing evidence and event previews does not send messages.

Verify both matches and exclusions: a qualifying first session, a first session below the threshold followed by a qualifying later session, a zero-message first session, and counts split across sessions. Use real available evidence. If an example is unavailable, record that check as unverified; never invent customers or test data. Distinguish historical preview, current source validation and deployment readiness in the setup report. A valid draft does not prove monitoring is running. Preserve the same routine ID and request, save the returned revision, and read it back before reporting completion.
`,
};
