export const agentKitVersion = '0.2.1';
// The setup handoff pins the CLI with remote sign-in support.
export const cliVersion = '0.1.5';
export type SetupRequest = { apiUrl: string; organizationId: string; routineId?: string; revision?: number; request: string; trackingOnly?: boolean; trackingSourceId?: string };
export function setupPrompt(input: SetupRequest): string {
  const endpoint = new URL('/api/mcp', input.apiUrl).href;
  return `${input.trackingOnly ? 'Configure only the missing o11 tracking in this application repository. Do not create, edit or activate a routine.' : 'Configure my o11 routine in the workspace below and add missing tracking in this application repository.'}

Workspace: ${input.organizationId}
${input.routineId ? `Routine: ${input.routineId}${input.revision !== undefined ? `\nCopied revision: ${input.revision}` : ''}` : input.trackingOnly ? 'Use this workspace’s existing sources.' : 'Create an inactive routine and reuse its returned ID.'}
${input.trackingSourceId ? `Tracking source: ${input.trackingSourceId}\n` : ''}MCP: ${endpoint}
Tracking endpoint: ${new URL('/api/tracking/events', input.apiUrl).href}
${input.routineId && !input.trackingOnly ? `Return to this routine: ${new URL(`/dashboard/signals?routine=${encodeURIComponent(input.routineId)}`, input.apiUrl).href}\n` : ''}Setup guide: ${new URL('/api/agent-docs/setup', input.apiUrl).href}
CLI version: ${cliVersion}
Tracking SDK version: ${agentKitVersion}

Before configuring anything, read this repository's AGENTS.md and applicable instructions, inspect existing code, and fetch current SDK/API documentation. Follow repository rules for checks, secrets, infrastructure and approval. Complete authorized local implementation and validation before requesting any required deployment or production approval. Do not deploy, run remote database commands, activate routines, or contact people without authorization for that action. Then review my request and the available documentation and sources. If my instructions are unclear or you need more information, ask me concise questions before making the affected changes. Do not guess missing requirements; continue only work that does not depend on my answers.

1. Prefer an available o11 MCP connection. Call o11_setup and verify the workspace. If your client cannot use MCP, use the published @o11/cli@${cliVersion}: o11 login --server ${endpoint}, then o11 tools list and o11 call TOOL --input FILE. CLI output is JSON. o11 mcp is also available as a local MCP server. Before browser sign-in, check whether this agent runs on a VM, over SSH or in a container. Check o11 --help for remote sign-in support. In a supported build, start o11 login --no-browser, keep that process running, and ask me to approve access and paste the sign-in code back here. Submit the code with o11 login --input FILE|- on this same host; keep code files private and delete them after use. If the installed CLI lacks this option, use a supported build or arrange callback port forwarding before presenting a link. Do not send me to an unreachable localhost callback. Verify o11 status before saying the connection is complete. Never print or commit credentials.
2. Read o11_docs for setup, routines, signals, tracking and the relevant source. Discover current capabilities and exact tool input schemas. Fetch the latest routine before editing; preserve my original request and unrelated edits. Read setupReport.scope.requestedBehavior as the saved detection request and honor scope.resolution unless I ask to change it. Reconcile these with any later edits to my original request, preserving unrelated follow-ups. A historical setup report is not current validation. Inspect descriptionDocument for the IDs of sources mentioned in my request; resolve them against signals_sources. Read existing source schemas and bounded samples. Reuse existing PostHog/database data before adding SDK tracking. Product database access must remain read-only.
3. ${input.trackingOnly ? 'Discover and register only the missing source events for the behavior below. Do not create or modify routine settings.' : 'Configure the requested routine: detection, identity, timing and any requested persona/sender, channels, tools, messages, follow-ups and stopping conditions. Preserve the saved deliveryMode. manual_review means the user reviews matching sessions and contacts customers themselves; sessions_only means detection with messaging off. These modes must not activate automatic outreach. Change back to automatic only when I explicitly ask. For a request to find sessions only, save detection without adding unsolicited messaging; report any limits on automatic execution. Edit the structured definitions directly; do not invoke another configuration agent.'} Unsupported requirements must be reported explicitly, never approximated silently.
4. If tracking is missing, register its event definition, install @o11/tracking@${agentKitVersion}, and instrument real successful operations in this repository. Follow the SDK documentation for stable event IDs, customer identity, server secrets and retries. Reuse the specified tracking source ID. Create a named, expiring local-development key with only required scopes; explicitly set environment=test. Never reuse production credentials locally. Synchronize actual verified contacts, recorded channel/purpose permissions and their evidence using identify; analytics identity alone is not permission. Use stable operation IDs and monotonically versioned full profile snapshots. Implement durable application outbox retries and poll receipt status: HTTP 202 means queued, not processed. Only attest coverage after the application outbox is fully drained through that time; absence detection requires continuous coverage and a grace period. Prepare a separate production key and server secret installation. For rotation keep at most two keys, verify replacement receipts then revoke the old key. Keep production installation subject to repository approval. With CLI credential calls, use --output-file to save the result privately instead of printing secrets. Run this repository's checks. Keep secrets out of browser bundles, messages and source control.
5. ${input.trackingOnly ? 'Verify the source configuration and report the received and missing events.' : 'Validate the full saved routine and preview its matches without contacting customers. Save an inactive draft and return its dashboard link and a concise summary.'} Verify received tracking through o11; code changes alone do not prove deployment. Report waiting dependencies honestly. Activate or deploy only if I explicitly authorize that action.
6. Reuse the same routine ID, revisions and mutation operation IDs.${input.routineId && !input.trackingOnly ? ' Configure the Routine ID above even if another routine has the same description. Do not create a replacement routine. Before reporting completion, read that exact routine back, verify the requested detection and follow-ups are saved, and validate its returned revision. Report the routine ID, saved revision, validation result, preview result and any remaining blockers, with the return link above. If saving or verification fails, report setup as incomplete.' : ''} After a timeout, inspect operation status and saved state before retrying, including when switching from MCP to CLI. A permission or validation error is not a reason to bypass checks.

${!input.trackingOnly ? `7. Save a setupReport on that same routine so its dashboard shows the result. If creating a routine, get its ID first, then save the report. Follow the discovered save schema: routineId, revision (the revision returned by this save, normally the input revision plus one), checkedAt (ISO timestamp), tracking { status, summary, pullRequestUrl? }, blockers [{ title?, action?, message, fixLabel, fixUrl?, owner?, nextStep? }], limitations [], optional scope { supportedBehavior, requestedBehavior, resolution? }, and optional preview { matchedSessions, windowSeconds, checkedAt }. Use tracking status reused only when existing received data covers the saved detection and no code change or pull request is needed; verified only after new tracking is received through o11. Use waiting_for_code, waiting_for_merge (include the actual pullRequestUrl), or waiting_for_deploy for unfinished changes. Keep titles and fix labels short. Give blockers a typed action: clarify_scope for an unresolved meaning (include scope with both behaviors); review_delivery for runtime or sender readiness; configure_signal for missing tracking; configure_routine for other incomplete settings. Leave a new scope resolution unset for me to choose. Preserve an existing choice; do not silently narrow my request. For every blocker, state the diagnosed cause in message, set owner to you, coding_agent, server_operator, or provider_admin, and put the exact required change in nextStep. If the cause is unknown, say what check is missing; never guess a provider-account problem. If the requirement cannot be met, explain why and what supported alternative exists. A CTA must lead to the required change or explain who must make it. Include the exact remaining action and real links; never invent a PR or infer deployment from valid configuration. Put unsupported behavior and any narrower observable behavior in limitations, and unresolved requested requirements in blockers. Fix what you can within my authorization before handing a blocker back. Delivery disabled by policy or unavailable runtime remains blocked; do not bypass it. After saving the report, read the same routine again and validate that returned revision. The report records evidence; it does not authorize activation or prove a deployment.

` : ''}${input.trackingOnly ? 'Behavior to instrument:' : 'My exact routine request (preserve this as the routine description):'}
${input.request}`;
}
