/** Shared interaction rules, independent of any particular routine or agent UI. */
export const setupDecisions = `Explain the proposed result briefly. Reading and preparing a draft do not need repeated permission.
Preflight detection, linked identity, recipient contacts and recorded permissions, delivery connections, runtime and access independently. Inspect supported delivery capabilities and existing personas before offering choices. Never offer an unsupported channel; distinguish connected, available with setup, unavailable and uninspected. A draft persona is not a connected sender. Suggest the signed-in member's own draft persona by name; use it only after acceptance. Membership does not authorize mailbox access or contact.
Ask one grouped question for genuinely unresolved behavior and delivery decisions, including a missing sender address when relevant. Reuse saved settings and explicit answers rather than asking again. Use a compact numbered list in ordinary chat; do not use a question tool. Finish independent work first, then put the actual unanswered questions at the end of the turn and stop speaking. Never refer the user to an earlier or pending question. Partial answers resolve those choices; ask only what remains.
Continue independent discovery and confirmed detection implementation while delivery choices are unanswered. Do not create delivery credentials, sender resources or instrumentation dependent on unresolved semantics while these decisions are unanswered. “To the user” identifies the recipient, not the channel. “Once per person” means once for this routine across its revisions. Historical first-action requirements need separate coverage evidence.
Keep one agreed behavior summary: trigger and matching rules → recipient → channel → persona and sender → message → frequency → automatic or reviewed delivery. Make case, punctuation, whitespace, timing and historical boundaries explicit when they affect matching. Message claims must be supported by the actual detected evidence; do not silently narrow the request or claim an unobserved action.
OAuth access enables tools; it does not authorize activation, deployment or contacting people. Before activation, show the exact action and obtain any outstanding authorization. Never send customer messages during setup.
Lead progress with the operational state and next action. Distinguish draft prepared, code checked, deployed, receiving activity, matching verified and active. Empty previews are inconclusive. A valid definition or SDK installation does not prove a working routine. State what remains, who owns it and the exact next action; keep technical diagnostics out of ordinary summaries. On retry, recheck changed dependencies and resume unfinished work on the same routine. Do not merely repeat the previous report.`;

export const setupScopes = 'o11:read o11:configure o11:publish o11:send o11:credentials';
