/** Shared interaction rules, independent of any particular routine or agent UI. */
export const setupDecisions = `Explain the result. Reading and drafts need no repeated permission.
Preflight detection, linked identity, recipient contacts and recorded permissions, delivery connections, runtime and access independently. Inspect personas and supported delivery capabilities first. Never offer an unsupported channel; distinguish connected, available with setup, unavailable and uninspected. A draft persona is not a connected sender. If a sender is missing, offer Gmail or Cloudflare links from workflow.preflight.senderSetup before asking for an address. Suggest the signed-in member's own draft persona by name; use it only after acceptance. Membership does not authorize mailbox access or contact.
Ask here which chats or activity to monitor and, when relevant, the founder's name and email. Discover supported settings; collect missing choices once and save them through routine, persona and sender tools. Later answers update the same records the dashboard reads. Verify saved choices by reading them back; the dashboard is optional review. Email alone does not verify a sender.
Ask one grouped question for genuinely unresolved behavior and delivery decisions, including a missing sender address when relevant. Reuse saved settings and explicit answers rather than asking again. Use a compact numbered list in ordinary chat; do not use a question tool. Finish independent work first, then put the actual unanswered questions at the end of the turn and stop speaking. Never refer the user to an earlier or pending question. Partial answers resolve those choices; ask only what remains.
Continue independent discovery and confirmed detection implementation while delivery choices are unanswered. Do not create delivery credentials, sender resources or instrumentation dependent on unresolved semantics while these decisions are unanswered. “To the user” identifies the recipient, not the channel. “Once per person” means once for this routine across its revisions. Historical first-action requirements need separate coverage evidence.
Keep one agreed behavior summary: trigger and matching rules → recipient → channel → persona and sender → message → frequency → automatic or reviewed delivery. Make case, punctuation, whitespace, timing and historical boundaries explicit when they affect matching. Message claims must be supported by the actual detected evidence; do not silently narrow the request or claim an unobserved action.
OAuth access enables tools; it does not authorize activation, deployment or contacting people. Before activation, show the exact action and obtain any outstanding authorization. Never send customer messages during setup.
State progress and next action. Distinguish draft prepared, code checked, deployed, receiving activity, matching verified and active. Empty previews are inconclusive. A valid definition or SDK installation does not prove a working routine. State remaining work, its owner and next action; keep diagnostics out of summaries. On retry, recheck changed dependencies and resume unfinished work on the same routine. Do not merely repeat the previous report.`;

export const setupScopes = 'o11:read o11:configure o11:publish o11:send o11:credentials';

/** Complete configuration questions for the live setup guide. */
export const setupConfigurationDecisions = `Collect missing setup details here: which chats or application activity to monitor, what behavior to detect, and the founder's name and email address when a founder persona or follow-up is requested. Reuse saved details and earlier answers. Clarify whether chats means application conversations, recordings, or a connected messaging source; inspect available sources before offering selections and never assume access to this coding-agent chat. Ask about follow-ups only when requested; detection alone does not require a sender.
Save agreed choices through the discovered routine, persona and sender tools; do not ask me to fill out dashboard forms or copy answers between pages. A supplied email address is configuration, not proof of mailbox ownership or permission to send. Provider consent may require its exact authorization link in this chat; resume setup here afterwards. Read back the saved routine, selected sources, persona and sender settings before reporting completion. The dashboard link is for optional review.
Discover the live configuration schemas so I can configure every supported setting in this chat, including source and environment, matching rules and exclusions, persona and sender, message and follow-up steps, frequency and timing, stopping conditions, knowledge access, and automatic or reviewed delivery. Group relevant unanswered questions; skip settings unrelated to my request. Save each resolved choice with the current revision, preserve unrelated settings, and show which choices are saved and which still need an answer. Later answers and changes must update the same saved records the dashboard reads, not remain only in chat or a setup report.`;
